Nc news ticket#7
reece-b4/NC-News-public pull request #5
Opened 2022-02-15 14:56 UTC by reece-b4

2022-02-15 15:33 UTC, cjplatten reviewed
See comment

2022-02-15 15:33 UTC, cjplatten commented on __tests__/app.test.js
> +    });
what happens if the patch request is sent with the wrong key or an empty object?

2022-02-16 10:42 UTC, popatre requested changes

2022-02-16 10:42 UTC, popatre commented on __tests__/app.test.js
> +            topic: "mitch",
Should be an easy one - but have you tested if it actually increments the votes?
At the moment, all the tests check that is decrements.

2022-02-16 10:42 UTC, popatre commented on __tests__/app.test.js
> +          expect(res.body.msg).toBe("bad request");
Test - what if there are more than one key on the object? e.g. inc_votes and title. 

It should be handled already, but good to show its been considered.

2022-02-16 10:43 UTC, reece-b4 commented on __tests__/app.test.js
> +            topic: "mitch",
I have tested yeah I actually just changed the test but can add it in easily

2022-02-16 11:31 UTC, Augs0 approved these changes
Just to note that you only need one 404 test globally - no need to use this on every endpoint

2022-02-16 11:31 UTC, merged